CREATE TABLE `appointments` (
  `id` VARCHAR(191) NOT NULL,
  `businessId` VARCHAR(191) NOT NULL,
  `staffUserId` VARCHAR(191) NULL,
  `clientId` VARCHAR(191) NULL,
  `itemId` VARCHAR(191) NULL,
  `serviceName` VARCHAR(200) NOT NULL,
  `startAt` DATETIME(3) NOT NULL,
  `endAt` DATETIME(3) NOT NULL,
  `status` ENUM('scheduled', 'completed', 'cancelled', 'no_show') NOT NULL DEFAULT 'scheduled',
  `priceOverride` DECIMAL(12, 2) NULL,
  `vatRate` DECIMAL(4, 2) NULL,
  `notes` TEXT NULL,
  `convertedDocumentId` VARCHAR(191) NULL,
  `reminderSentAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `appointments_businessId_startAt_idx` (`businessId`, `startAt`),
  KEY `appointments_businessId_status_idx` (`businessId`, `status`),
  KEY `appointments_staffUserId_startAt_idx` (`staffUserId`, `startAt`),
  KEY `appointments_clientId_idx` (`clientId`),
  CONSTRAINT `appointments_businessId_fkey` FOREIGN KEY (`businessId`) REFERENCES `businesses`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `appointments_staffUserId_fkey` FOREIGN KEY (`staffUserId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `appointments_clientId_fkey` FOREIGN KEY (`clientId`) REFERENCES `clients`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `appointments_itemId_fkey` FOREIGN KEY (`itemId`) REFERENCES `items`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `appointments_convertedDocumentId_fkey` FOREIGN KEY (`convertedDocumentId`) REFERENCES `documents`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
